    <message name="IDS_PAGE_INFO_SECURITY_TAB_ECH_ACCEPTED" desc="Titanium: shown in connection details when the TLS connection used Encrypted Client Hello.">
      The site name was encrypted using Encrypted Client Hello (ECH).
    </message>
    <message name="IDS_PAGE_INFO_SECURITY_TAB_ECH_NOT_USED" desc="Titanium: shown in connection details when the TLS connection did not use Encrypted Client Hello.">
      The site name was sent unencrypted. Encrypted Client Hello (ECH) was not used.
    </message>
